In [5]:
# NAIVEBAYES

In [81]:
import pandas as pd
import numpy as np 

In [83]:
data = pd.read_excel("C:\\Users\\SIT\\Downloads\\Churn.xlsx")



In [85]:
import os
os.getcwd()

'C:\\Users\\SIT\\DWM-prac4'

In [87]:
data.head()

Age  Tenure  Monthly Spend Service Plan  Support Calls  Churned
0   22       1             20        Basic              2        0
1   25       3             40      Premium              1        0
2   30       2             50        Basic              3        0
3   35       5             60      Premium              0        1
4   40       7             80      Premium              1        0

In [89]:
data['Service Plan'].unique()

array(['Basic', 'Premium'], dtype=object)

In [95]:
data.columns

Index(['Age', 'Tenure', 'Monthly Spend', 'Service Plan', 'Support Calls',
       'Churned'],
      dtype='object')

In [99]:
data.drop('Service Plan',axis=1,inplace=True)

In [101]:
data.head()

Age  Tenure  Monthly Spend  Support Calls  Churned
0   22       1             20              2        0
1   25       3             40              1        0
2   30       2             50              3        0
3   35       5             60              0        1
4   40       7             80              1        0

In [107]:
x = data.iloc[:, :4].values

In [109]:
x

array([[ 22,   1,  20,   2],
       [ 25,   3,  40,   1],
       [ 30,   2,  50,   3],
       [ 35,   5,  60,   0],
       [ 40,   7,  80,   1],
       [ 45,   6,  75,   5],
       [ 28,   1,  30,   2],
       [ 50,   9, 100,   0],
       [ 60,  10, 120,   4],
       [ 33,   4,  55,   3],
       [ 38,   3,  65,   2],
       [ 26,   1,  25,   1],
       [ 29,   2,  45,   0],
       [ 31,   3,  55,   2],
       [ 32,   6,  70,   4],
       [ 41,   8,  85,   3],
       [ 34,   4,  50,   1],
       [ 44,   7,  90,   0],
       [ 37,   2,  60,   3],
       [ 43,   5,  70,   2],
       [ 29,   1,  35,   4],
       [ 31,   3,  50,   1],
       [ 48,   6,  80,   3],
       [ 36,   4,  55,   2],
       [ 39,   5,  65,   1],
       [ 47,   8,  95,   2],
       [ 50,   9, 105,   1],
       [ 55,  10, 110,   0],
       [ 60,   7,  95,   3],
       [ 24,   1,  20,   2],
       [ 27,   3,  40,   1],
       [ 29,   2,  45,   2],
       [ 33,   5,  55,   0],
       [ 41,   6,  75,   4],
       [ 47,  

In [115]:
y = data.iloc[:,4].values

In [117]:
y

array([0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0,
       1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0],
      dtype=int64)

In [119]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x,y,test_size=0.25,random_state=0)

# from sklearn.preprocessing import StandardScaler
# sc = StandardScaler() 
# x_train=sc.fit_transform(x_train)
# x_test = sc.transform(x_test)




In [121]:
print(x_train)
print('*'*50)
print(x_test)

[[ 29   1  35   4]
 [ 55   9 100   3]
 [ 30   2  50   3]
 [ 52   8  90   1]
 [ 37   2  60   3]
 [ 41   8  85   3]
 [ 48   6  80   3]
 [ 34   4  50   1]
 [ 50   7  90   1]
 [ 60  10 120   4]
 [ 31   3  55   2]
 [ 45   6  75   5]
 [ 44   7  90   0]
 [ 33   5  55   0]
 [ 32   6  70   4]
 [ 42   4  50   3]
 [ 50   9 100   0]
 [ 47   8  90   1]
 [ 25   3  40   1]
 [ 50   9 105   1]
 [ 29   2  45   0]
 [ 41   6  75   4]
 [ 39   5  65   1]
 [ 28   1  30   2]
 [ 36   4  55   2]
 [ 31   3  50   1]
 [ 43   5  70   2]
 [ 33   4  55   3]
 [ 54   8  95   4]
 [ 36   5  60   2]
 [ 35   5  60   0]
 [ 22   1  20   2]]
**************************************************
[[ 27   3  40   1]
 [ 38   3  65   2]
 [ 55  10 110   0]
 [ 40   7  80   1]
 [ 38   3  65   2]
 [ 47   8  95   2]
 [ 60   7  95   3]
 [ 26   1  25   1]
 [ 49   6  85   0]
 [ 29   2  45   2]
 [ 24   1  20   2]]


In [126]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()
model.fit(x_train,y_train)

GaussianNB()

In [128]:
y_pred= model.predict(x_test)
y_pred

array([0, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0], dtype=int64)

In [130]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test , y_pred)
cm

array([[5, 2],
       [1, 3]], dtype=int64)

In [134]:
y_pred= model.predict([[22 , 1 , 20  , 2]])
print(y_pred)

[0]
